[package]
name = "bond"
version = "0.1.0"
edition = "2021"
license = "BSD-2-Clause-Patent"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
futures = "0.3.17"
k8s-openapi = { version = "0.13.1", default-features = false, features = ["v1_22"] }
kube = { version = "0.63.2", features = ["derive", "runtime"] }
kube-runtime = { version = "0.63.2", default-features = false }
log = "0.4.14"
schemars = "0.8.7"
serde = "1.0.130"
serde_json = "1.0.70"
thiserror = "1.0.30"
tokio = { version = "1.13.0", default-features = false, features = ["macros", "rt-multi-thread"] }
